
(function () {
    $(document).ready(function () {
      $('#show1').slideDown();
      $(".bar").on("click", function () {
        $(this).siblings().slideToggle();
        $(this).parent().siblings().find(".show").slideUp();
        $(this).toggleClass("active");

        $(this).parent().siblings().find(".bar").removeClass("active");
        $(this).children().toggleClass("bi bi-caret-up-fill");
        $(this).children().toggleClass("bi bi-caret-down-fill");
        $(this).parent().siblings().find("i").removeClass("bi bi-caret-up-fill");
        $(this).parent().siblings().find("i").addClass("bi bi-caret-down-fill");
      });
      $('#bar1').click(function(){
          $('#show2').slideUp();
          $('#show3').slideUp();
          $('#show4').slideUp();
      });
      $('#bar2').click(function(){
        $('#show1').slideUp();
        $('#show3').slideUp();
        $('#show4').slideUp();
      });
      $('#bar3').click(function(){
        $('#show1').slideUp();
        $('#show2').slideUp();
        $('#show4').slideUp();
      });
      $('#bar4').click(function(){
        $('#show1').slideUp();
        $('#show2').slideUp();
        $('#show3').slideUp();
      });
      $('#bt1-1').click(function(){
        $('.show1_img').attr('src','image/ppt_image1-3.png');
        $(this).remove();
        $('#bd1-1').fadeIn("slow");
      });
      $('#bd1-1').click(function(){
        $('.show1_img').attr('src','image/ppt_image1-4.png');
        $(this).remove();
        $('#bt1-2').fadeIn("slow");
      });
      $('#bt1-2').click(function(){
        $('.show1_img').attr('src','image/ppt_gif1.gif');
        $('.show1_img').css('margin-left','30px');
        $(this).remove();
      });
      $('#bd2-1').click(function(){
        $('.show2_img').attr('src','image/ppt_image2-2.png');
        $(this).remove();
        $('#bt2-1').fadeIn("slow");
      });
      $('#bt2-1').click(function(){
        $('.show2_img').attr('src','image/ppt_image2-3.png');
        $('.show2_img').css('margin-top','100px');
        $('.show2_img').css('margin-left','100px');
        $(this).remove();
        $('#bd2-2').fadeIn("slow");
      });
      $('#bd2-2').mousedown(function(event){
        switch (event.which) {
          case 3:
            $('.show2_img').attr('src','image/ppt_image2-4.png');
            $(this).remove();
            $('#bd2-3').fadeIn("slow");
            break;
        }
      });
      $('#bd2-3').click(function(){
        $('.show2_img').attr('src','image/ppt_image2-5.png');
        $('.show2_img').css('margin-top','120px');
        $('.show2_img').css('margin-left','60px');
        $(this).remove();
        $('#bd2-4').fadeIn("slow");
      });
      $('#bd2-4').click(function(){
        $('.show2_img').attr('src','image/ppt_image2-6.png');
        $(this).remove();
        $('#bt2-2').fadeIn("slow");
      });
      $('#bt2-2').click(function(){
        $('.show2_img').attr('src','image/ppt_image2-7.png');
        $(this).remove();
        $('#bt2-3').fadeIn("slow");
      });
      $('#bt2-3').click(function(){
        $('.show2_img').attr('src','image/ppt_image2-8.png');
        $(this).remove();
        $('#bd2-5').fadeIn("slow");
      });
      $('#bd2-5').click(function(){
        $('.show2_img').attr('src','image/ppt_gif2.gif');
        $('.show2_img').css('margin-left','30px');
        $(this).remove();
      });
      $('#bd3-1').click(function(){
        $('.show3_img').attr('src','image/ppt_image3-2.png');
        $(this).remove();
        $('#bt3-1').fadeIn("slow");
      });
      $('#bt3-1').click(function(){
        $('.show3_img').attr('src','image/ppt_image3-3.png');
        $(this).remove();
        $('#bd3-2').fadeIn("slow");
      });
      $('#bd3-2').click(function(){
        $('.show3_img').attr('src','image/ppt_image3-4.png');
        $(this).remove();
        $('#bd3-3').fadeIn("slow");
      });
      $('#bd3-3').click(function(){
        $('.show3_img').attr('src','image/ppt_image3-5.png');
        $(this).remove();
        $('#bd3-4').fadeIn("slow");
      });
      $('#bd3-4').click(function(){
        $('.show3_img').attr('src','image/ppt_image3-6.png');
        $(this).remove();
        $('#bt3-2').fadeIn("slow");
      });
      $('#bt3-2').click(function(){
        $('.show3_img').attr('src','image/ppt_gif3.gif');
        $('.show3_img').css('margin-left','30px');
        $(this).remove();
      });
      $('#bt4-1').click(function(){
        $('.show4_img').attr('src','image/ppt_image4-2.png');
        $(this).remove();
        $('#bd4-1').fadeIn("slow");
      });
      $('#bd4-1').click(function(){
        $('.show4_img').attr('src','image/ppt_image4-3.png');
        $(this).remove();
        $('#bt4-2').fadeIn("slow");
      });
      $('#bt4-2').click(function(){
        $('.show4_img').attr('src','image/ppt_image4-4.png');
        $(this).remove();
        $('#bd4-2').fadeIn("slow");
      });
      $('#bd4-2').click(function(){
        $('.show4_img').attr('src','image/ppt_image4-5.png');
        $(this).remove();
        $('#bd4-3').fadeIn("slow");
      });
      $('#bd4-3').click(function(){
        $('.show4_img').attr('src','image/ppt_image4-6.png');
        $(this).remove();
        $('#bt4-3').fadeIn("slow");
      });
      $('#bt4-3').click(function(){
        $('.show4_img').attr('src','image/ppt_gif4.gif');
        $('.show4_img').css('margin-left','30px');
        $(this).remove();
      });
      $('.vdTag1').click(function(){
        $('.vid').attr('src','https://www.youtube.com/embed/rzPalb0LIk4');
      });
    });
 })();