setTimeout(function () {
    return window.scrollTo(0, 0);
  }, 150);
(function () {
    $(document).ready(function () {
        $('body').css('overflow','hidden');
        $('.gobt').click(function(event){
            event.preventDefault();
            $('body').css('overflow','auto');
        });
        $('.yel').click(function(){
            $('.gr').removeClass('gr_click');
            $('.bl').removeClass('bl_click');
            $('.red').removeClass('red_click');
            $(this).addClass('yel_click');
            $('.page1').css("display","flex");
            $('.page2').css("display","none");
            $('.page3').css('display','none');
            $('.page4').css('display','none');
        });
        $('.gr').click(function(){
            $('.yel').removeClass('yel_click');
            $('.bl').removeClass('bl_click');
            $('.red').removeClass('red_click');
            $(this).addClass('gr_click');
            $('.page1').css('display','none');
            $('.page2').css('display','flex');
            $('.page3').css('display','none');
            $('.page4').css('display','none');
        });
        $('.bl').click(function(){
            $('.gr').removeClass('gr_click');
            $('.yel').removeClass('yel_click');
            $('.red').removeClass('red_click');
            $(this).addClass('bl_click');
            $('.page1').css('display','none');
            $('.page2').css('display','none');
            $('.page3').css('display','flex');
            $('.page4').css('display','none');
        });
        $('.red').click(function(){
            $('.gr').removeClass('gr_click');
            $('.bl').removeClass('bl_click');
            $('.yel').removeClass('el_click');
            $(this).addClass('red_click');
            $('.page1').css('display','none');
            $('.page2').css('display','none');
            $('.page3').css('display','none');
            $('.page4').css('display','flex');
        });
        $('#v3s1').click(function(){
            $('#v3s2').removeClass('gr_click');
            $(this).addClass('yel_click');
            $('#v3p2').css('display','none');
            $('#v3p1').css('display','flex');
        });
        $('#v3s2').click(function(){
            $('#v3s1').removeClass('gr_click');
            $(this).addClass('gr_click');
            $('#v3p1').css('display','none');
            $('#v3p2').css('display','flex');
        });
    });
 })();